# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1        
            - name: Install Node
              uses: actions/setup-node@v3  
              with: 
                node-version: 14
            - name: Install mocha
              run: npm install -g mocha
            - name: Install dependencies
              run: |
               npm install
            - name: "Run Test"
              run: |
               node ./node_modules/mocha/bin/mocha ./test/converter.js --reporter spec

